### ISSUE TITLE
migrate module to Vox Pupuli?

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-consul#576]
Hi @solarkennedy ,
did you ever consider to migrate the module to Vox Pupuli? That would enable more maintainers to review open issues and pull requests. You would not loose commit access to the repo. Vox Pupuli is a community of module developers, we maintain ~140 modules (the website is https://voxpupuli.org/). Please let me know what you think about it.

**Comment by genebean** [comment]
Happy Thursday @solarkennedy! I was curious what you thought about this too.

**Comment by solarkennedy** [comment]
Hmm. Still thinking about it.

**Comment by solarkennedy** [comment]
@bastelfreak I think I'm ready to hand this over. 
I guess just email me with steps I need to do to make it happen?

**Comment by bastelfreak** [comment]
hey!
I invited you to the correct GitHub org. You should be able to migrate the GitHub repository. We have the documentation available at https://voxpupuli.org/docs/migrate_module/. If you've questions just ping me here/ or via email or on slack/IRC (#voxpupuli on Libera IRC or https://slack.puppet.com/)

**Comment by bastelfreak** [comment]
@solarkennedy ping :)

**Comment by solarkennedy** [comment]
This has been transferred to the voxpupuli github org.
@bastelfreak I'll leave it to you to close this issue when you are happy with any followup stuff.
