### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by jas01** [voxpupuli/puppet-consul#600]
Not really a issue, more a question. 

On the [https://forge.puppet.com/modules/KyleAnderson/consul](https://forge.puppet.com/modules/KyleAnderson/consull)
this module are tag as _deprecated_ but here I can see a new version (tag 7.1.0) who do not appear on puppet forge. 

What are the actual status of this project currently ?

**Comment by kenyon** [comment]
Here is the Forge page: https://forge.puppet.com/modules/puppet/consul
